### ISSUE TITLE
Jquery serialize assumes multiple values are arrays... (patch to alter behavior)

### ISSUE THREAD

**Issue by famgam** [cowboy/jquery-misc#3]
I made a slight tweak to the way multiple named values are used. For example, if you have 3 text inputs with **name="test"** then your POST/GET looks like test=something&test=somethingelse&test=somethingelseagain 

The issue with this is that some forms explicitly use square brackets like this **test[]** to provide multiple values are read at the server level.

Sooo, when jquery makes an object/array serialization it assumes multiple values _must_ be an array instead of actually just multiple values. This version assumes that if there are multiple names, but are _not_ explicitly setup as arrays (by use of square brackets in names) then the last values is used as a string value, instead of an array of all values.

``` javascript
    (function($,undefined){
        $.fn.serializeObject = function(){
            var obj = {};
            $.each( this.serializeArray(), function(i,o){
                var n = o.name,
                    v = o.value;
                    obj[n] = obj[n] === undefined ? v
                        : $.isArray( obj[n] ) ? obj[n].concat( v )
                        : n.indexOf("[")!=-1 ? [ obj[n], v ]
                        : v;
            });
            return obj;
        };
    })(jQuery);
```

I realize this is not what everyone wants for the serializeObject behaviour, but it's what I needed, so it maybe helpful with a bool flag or param of some kind to turn this feature on when needed.

NOTE: I used hidden fields to submit empty checkbox values in standard page submit forms. When I went ajax with the form, Prototype JS Serialize behaved the same way as the html form submission, but then I migrated to jQuery, and jQuery Serialize turned multiple names into arrays... hence this fix.

**Comment by cowboy** [comment]
This plugin has a very specific use, if you want custom behavior just write your own plugin!
